# Generated by Django 4.1.7 on 2023-04-26 16:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=10),
        ),
    ]
